-- Initial seed data for the database-backed landing page content.
-- Only news and gallery data are connected to Supabase in the current website.

insert into gallery_items (src, title, category, description, status, "order") values
('/assets/hero_athlete.jpg','G.S Gacuba II A Basketball Star Athlete','Sports & Athletics','Our dedicated student athlete holding court at G.S Gacuba II A sports court.','Published',0),
('/assets/gacuba_basketball.jpg','Rubavu District Basketball Inter-School Tournament','Competition','G.S Gacuba II A basketball team competing in regional school matches.','Published',1),
('/assets/gacuba_mpc.jpg','MPC Computer Science & Physics Laboratory','Academics','Students engaging in computer programming and physical science practicals.','Published',2),
('/assets/gacuba_campus.jpg','Gisenyi Sector School Assembly Grounds','Campus Grounds','Students assembled on the green day-school campus in Gisenyi sector.','Published',3),
('/assets/lake_kivu.jpg','Proximity to Lake Kivu & Gisenyi City','Environment','Scenic Rubavu landscape providing a peaceful learning environment.','Published',4);

insert into news_items (title, date, category, summary, content, author, read_time, image_url, status, published_at) values
('G.S Gacuba II A Basketball Team Advances to Rubavu District Finals','July 20, 2026','Sports & Athletics','The G.S Gacuba II A basketball varsity squad put on a stellar performance in the Rubavu inter-school playoffs, securing a spot in the district finals.',array['Groupe Scolaire Gacuba II A (G.S Gacuba II A) celebrated an outstanding athletic milestone as the school''s basketball team defeated top regional contenders to secure their place in the Rubavu District Inter-School Championship finals.','Lead student athlete #24 delivered an exceptional performance on court, exemplifying the dedication, athletic power, and academic balance that G.S Gacuba II A instills in all its day scholars.','Headmaster Jean-Baptiste Nsengiyumva praised the players, emphasizing that participation in competitive sports builds essential life skills like discipline, teamwork, and mental fortitude.','Supporters, parents, and fellow scholars in Gisenyi sector are invited to cheer on the team during the upcoming finals held near the TTC Gacuba II sports complex.'],'Sports Department & Athletics Council','3 min read','/assets/hero_athlete.jpg','Published',now()),
('REB & NESA Guidelines: A''Level MPC and HGL Subject Combination Briefing','June 28, 2026','Academic Bulletin','Official guidance for Senior 3 candidates selecting Advanced Level combinations (Math, Physics, Computer Science & History, Geography, Language) for the upcoming academic year.',array['In alignment with guidelines published by the Rwanda Education Board (REB) and the National Examination and School Inspection Authority (NESA), G.S Gacuba II A held an orientation session for Ordinary Level S3 students.','The session outlined upper secondary combination entry criteria for the Math, Physics, Computer Science (MPC) and History, Geography, Language (HGL) streams.','Students aiming for university STEM faculties are encouraged to strengthen their foundational calculus and physics scores, while humanities scholars preparing for law, development studies, and education receive tailored mentorship.','Details regarding national examination schedules and subject syllabi can be viewed on the official NESA portal.'],'Academic Director & NESA Inspection Desk','4 min read','/assets/gacuba_mpc.jpg','Published',now()),
('TTC Gacuba II & G.S Gacuba II A Educational Mentorship Partnership','May 15, 2026','Community & Education','Collaborative academic mentorship initiative with neighbor TTC Gacuba II focusing on teacher training, Early Childhood Development (ECD) practicals, and peer tutoring.',array['Groupe Scolaire Gacuba II A has expanded its collaborative educational partnership with neighboring Teacher Training College (TTC Gacuba II) in Gisenyi sector.','The initiative enables student teachers specializing in Early Childhood Development (ECD) and secondary pedagogy to engage in practical peer tutoring and classroom observation.','This local synergy enhances learning outcomes for O''Level and A''Level students while reinforcing G.S Gacuba II A''s role as a cornerstone government-aided day school in Rubavu District.'],'Community Liaison Desk','3 min read','/assets/gacuba_campus.jpg','Published',now());
